<?php
if($_SERVER['REQUEST_METHOD']=="POST")
{	

    $subject = "Enquire Form Submission from Impresario DMC";
    $title = stripslashes($_POST['title']);    
	  $c_name  = stripslashes($_POST['c_name']);
	  	 	$postcode = stripslashes($_POST['postcode']);
					$telephone = stripslashes($_POST['telephone']);
							$email = stripslashes($_POST['email']);
									$delegates = stripslashes($_POST['delegates']);
										$location = stripslashes($_POST['location']);
									$d_event = stripslashes($_POST['d_event']);
								$e_type = stripslashes($_POST['e_type']);
							$information = stripslashes($_POST['information']);						
    $toEemail = "nithya@impresario.co.in";

    
     // To send HTML mail, the Content-type header must be set
			     $headers  = 'MIME-Version: 1.0' . "\r\n";
			      $headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";
			      $headers .= "X-Mailer: Mail generated by:gotamarind.com\r\n";
			//       Additional headers
			      $headers .= 'Reply-To:'.$email."\r\n" .
			      $headers .= 'From: '.$email . "\r\n";    
			    $strMessageBody = '<span style="font-size:18px; color:#058935; ">';
			    $strMessageBody .='Title:</span><br><span style="font-size:14px;color:#000000; ">'.$title.'</span><br><br>';	
				$strMessageBody .= '<span style="font-size:18px; color:#058935; ">';
			    $strMessageBody .='Contact Name:</span><br><span style="font-size:14px;color:#000000; ">'.$c_name.'</span><br><br>';					
								
				$strMessageBody .= '<span style="font-size:18px; color:#058935; ">';
			    $strMessageBody .='Postcode:</span><br><span style="font-size:14px;color:#000000; ">'.$postcode.'</span><br><br>';
				$strMessageBody .= '<span style="font-size:18px; color:#058935; ">';
			    $strMessageBody .='Telephone :</span><br><span style="font-size:14px;color:#000000; ">'.$telephone.'</span><br><br>';	
				
				$strMessageBody .= '<span style="font-size:18px; color:#058935; ">';
			    $strMessageBody .='E-mail:</span><br><span style="font-size:14px;color:#000000; ">'.$email.'</span><br><br>';
				$strMessageBody .= '<span style="font-size:18px; color:#058935; ">';
			    $strMessageBody .='No. of Delegates:</span><br><span style="font-size:14px;color:#000000; ">'.$delegates.'</span><br><br>';
				$strMessageBody .= '<span style="font-size:18px; color:#058935; ">';
			    $strMessageBody .='Event Location:</span><br><span style="font-size:14px;color:#000000; ">'.$location.'</span><br><br>';
				$strMessageBody .= '<span style="font-size:18px; color:#058935; ">';
			    $strMessageBody .='Date of event:</span><br><span style="font-size:14px;color:#000000; ">'.$d_event.'</span><br><br>';
				$strMessageBody .= '<span style="font-size:18px; color:#058935; ">';
			    $strMessageBody .='Event Type:</span><br><span style="font-size:14px;color:#000000; ">'.$e_type.'</span><br><br>';
				$strMessageBody .= '<span style="font-size:18px; color:#058935; ">';
			    $strMessageBody .='Other Information:</span><br><span style="font-size:14px;color:#000000; ">'.$information.'</span><br><br>';
				
			     if(mail($toEemail, $subject, $strMessageBody, $headers)){		     
	 						header('Location:afterEnquiry.html');
			     }			 
}
?>
